name: Add merge comment to successful PRs for dependabot

on:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed

jobs:
  create_dependabot_comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Add merge comment for dependabot PRs
        id: add-merge-comment
        uses: jo-sm/at-dependabot-merge@v1
        with:
          run-id: ${{ github.event.workflow_run.id }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
